/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed models */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a model */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed AI providers */
        get: operations["listAiProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an AI provider */
        get: operations["getAiProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the config for an AI provider */
        patch: operations["updateAiProviderConfig"];
        trace?: never;
    };
    "/analysis/classification-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List classification providers */
        get: operations["listClassificationProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/classifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List classifiers */
        get: operations["listClassifiers"];
        put?: never;
        /** Create a classifier */
        post: operations["createClassifier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/classifiers/{classifierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a classifier */
        get: operations["getClassifier"];
        put?: never;
        post?: never;
        /** Delete a classifier */
        delete: operations["deleteClassifier"];
        options?: never;
        head?: never;
        /** Update a classifier */
        patch: operations["updateClassifier"];
        trace?: never;
    };
    "/media/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a media container
         * @description Creates an empty container that is ready to receive an upload.
         */
        post: operations["createMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/containers/{containerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a media container */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        /**
         * Delete a media container
         * @description All associated assets will be deleted.
         */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        /** Update a media container */
        patch: operations["updateMedia"];
        trace?: never;
    };
    "/media/containers/{containerId}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload an asset to a media container */
        put: operations["upload"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate links for media containers */
        post: operations["generateLinks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the contents of a media tree */
        get: operations["getTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search media containers */
        post: operations["searchMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List search indexes */
        get: operations["listSearchIndexes"];
        put?: never;
        /** Create a search index */
        post: operations["createSearchIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/indexes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a search index */
        delete: operations["deleteSearchIndex"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/vector-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed vector providers */
        get: operations["listVectorProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/vector-providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the config for a vector provider */
        patch: operations["updateVectorProviderConfig"];
        trace?: never;
    };
    "/storage/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage configs */
        get: operations["listStorageConfigs"];
        put?: never;
        /** Create a storage provider config */
        post: operations["createStorageConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/configs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a storage config */
        get: operations["getStorageConfig"];
        put?: never;
        post?: never;
        /** Delete a storage config */
        delete: operations["deleteStorageConfig"];
        options?: never;
        head?: never;
        /** Update a storage config */
        patch: operations["updateStorageConfig"];
        trace?: never;
    };
    "/storage/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed storage providers */
        get: operations["listStorageProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage units */
        get: operations["listStorageUnits"];
        put?: never;
        /** Create a storage unit */
        post: operations["createStorageUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/units/{storageUnitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a storage unit */
        get: operations["getStorageUnit"];
        put?: never;
        post?: never;
        /** Delete a storage unit */
        delete: operations["deleteStorageUnit"];
        options?: never;
        head?: never;
        /** Update a storage unit */
        patch: operations["updateStorageUnit"];
        trace?: never;
    };
    "/system/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system setup status */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AiModel: {
            /** @description The schema for classifier input, if the model supports classification */
            classifierInputSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description A brief description of the model
             * @example Claude Haiku 4.5 is a small, fast, and powerful model for text generation
             */
            description: string | null;
            /**
             * @description The fully qualified ID of the model
             * @example anthropic/claude-haiku-4-5-20251001
             */
            fullyQualifiedId: string;
            /**
             * @description The ID of the model
             * @example claude-haiku-4-5-20251001
             */
            id: string;
            /**
             * @description The display name of the model
             * @example Claude Haiku 4.5
             */
            name: string;
            /** @description The provider of the model */
            provider: components["schemas"]["AiProviderSummary"];
        };
        AiModelShort: {
            /**
             * @description A brief description of the model
             * @example Claude Haiku 4.5 is a small, fast, and powerful model for text generation
             */
            description: string | null;
            /**
             * @description The fully qualified ID of the model
             * @example anthropic/claude-haiku-4-5-20251001
             */
            fullyQualifiedId: string;
            /**
             * @description The ID of the model
             * @example claude-haiku-4-5-20251001
             */
            id: string;
            /**
             * @description The display name of the model
             * @example Claude Haiku 4.5
             */
            name: string;
        };
        AiModelSummary: {
            /**
             * @description The fully qualified ID of the model
             * @example anthropic/claude-haiku-4-5-20251001
             */
            fullyQualifiedId: string;
            /**
             * @description The ID of the model
             * @example claude-haiku-4-5-20251001
             */
            id: string;
            /**
             * @description The display name of the model
             * @example Claude Haiku 4.5
             */
            name: string;
            /** @description The provider of the model */
            provider: components["schemas"]["AiProviderSummary"];
        };
        AiProvider: {
            /**
             * @description The config values for the provider
             * @example {
             *       "apiKey": "sk-1234567890"
             *     }
             */
            config: {
                [key: string]: unknown;
            } | null;
            /**
             * @description The schema for the provider config
             * @example {
             *       "apiKey": {
             *         "label": "API Key",
             *         "type": "secret",
             *         "required": true
             *       }
             *     }
             */
            configSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            } | null;
            /**
             * @description The ID of the AI provider
             * @example anthropic
             */
            id: string;
            /**
             * @description An icon image of the AI provider
             * @example https://www.gstatic.com/pantheon/images/aiplatform/model_garden/icons/icon-anthropic-v2.png
             */
            image: string;
            /**
             * @description The models supported by the provider
             * @example [
             *       {
             *         "id": "claude-haiku-4-5-20251001",
             *         "name": "Claude Haiku 4.5",
             *         "fullyQualifiedId": "anthropic/claude-haiku-4-5-20251001"
             *       }
             *     ]
             */
            models: components["schemas"]["AiModelShort"][];
            /**
             * @description The name of the AI provider
             * @example Anthropic
             */
            name: string;
            /**
             * @description Whether the provider needs additional configuration
             * @example false
             */
            needsConfig: boolean;
        };
        AiProviderSummary: {
            /**
             * @description The ID of the AI provider
             * @example anthropic
             */
            id: string;
            /**
             * @description An icon image of the AI provider
             * @example https://www.gstatic.com/pantheon/images/aiplatform/model_garden/icons/icon-anthropic-v2.png
             */
            image: string | null;
            /**
             * @description The name of the AI provider
             * @example Anthropic
             */
            name: string;
            /**
             * @description Whether the provider needs additional configuration
             * @example false
             */
            needsConfig: boolean;
        };
        ClassificationProvider: {
            /** @description The schema for classifier input */
            classifierInputSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /** @description A brief description of the classification provider */
            description: string | null;
            /**
             * @description The display name of the classification provider
             * @example GPT-5 Nano
             */
            displayName: string;
            /**
             * @description The fully qualified ID of the classification provider
             * @example openai/gpt-5-nano-2025-08-07
             */
            fullyQualifiedId: string;
            /**
             * @description The ID of the classification provider
             * @example gpt-5-nano-2025-08-07
             */
            id: string;
            /**
             * @description Maximum file size in bytes
             * @example 52428800
             */
            maxFileSize: number;
            /**
             * @description The plugin ID that provides this classification provider
             * @example openai
             */
            pluginId: string;
            /**
             * @description Supported MIME types
             * @example [
             *       "image/jpeg",
             *       "image/png"
             *     ]
             */
            supportedMimeTypes: string[];
        };
        ClassificationProviderSummary: {
            /** @description A brief description of the classification provider */
            description: string | null;
            /**
             * @description The display name of the classification provider
             * @example GPT-5 Nano
             */
            displayName: string;
            /**
             * @description The fully qualified ID of the classification provider
             * @example openai/gpt-5-nano-2025-08-07
             */
            fullyQualifiedId: string;
            /**
             * @description The ID of the classification provider
             * @example gpt-5-nano-2025-08-07
             */
            id: string;
            /**
             * @description The plugin ID that provides this classification provider
             * @example openai
             */
            pluginId: string;
        };
        Classifier: {
            /**
             * Format: date-time
             * @description When the classifier was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description A brief description of the classifier
             * @example Tag general subjects like people, places, and things
             */
            description: Record<string, never> | null;
            /**
             * @description The ID of the classifier
             * @example sajl1kih6emtwozh8y0zenkj
             */
            id: string;
            /**
             * @description The input values to use for the model
             * @example {
             *       "name": "John Doe"
             *     }
             */
            modelInput: Record<string, never>;
            /**
             * @description The schema for the classifier input
             * @example {
             *       "name": {
             *         "label": "Name",
             *         "type": "string",
             *         "required": true
             *       }
             *     }
             */
            modelInputSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description The name of the classifier
             * @example general-tagging
             */
            name: string;
            /** @description The classification provider used by the classifier */
            provider: components["schemas"]["ClassificationProviderSummary"];
            /**
             * Format: date-time
             * @description When the classifier was last updated
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ClassifierRun: {
            /** @description The classifier that was used to run the classifier run */
            classifier: components["schemas"]["ClassifierShort"];
            /**
             * @description When the classifier run completed
             * @example 2025-01-01T00:00:00.000Z
             */
            completedAt: string | null;
            /**
             * Format: date-time
             * @description When the classifier run was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description The error message of the classifier run
             * @example An error occurred while running the classifier
             */
            errorMessage: string | null;
            /**
             * @description The ID of the classifier run
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description The result of the classifier run
             * @example {
             *       "tags": [
             *         "person",
             *         "car",
             *         "tree"
             *       ]
             *     }
             */
            result: {
                [key: string]: unknown;
            };
            /**
             * @description When the classifier run started
             * @example 2025-01-01T00:00:00.000Z
             */
            startedAt: string | null;
            /**
             * @description The status of the classifier run
             * @example SUCCESS
             * @enum {string}
             */
            status: "PROCESSING" | "SUCCESS" | "FAILED";
        };
        ClassifierShort: {
            /**
             * @description A brief description of the classifier
             * @example Tag general subjects like people, places, and things
             */
            description: Record<string, never> | null;
            /**
             * @description The ID of the classifier
             * @example sajl1kih6emtwozh8y0zenkj
             */
            id: string;
            /**
             * @description The name of the classifier
             * @example general-tagging
             */
            name: string;
        };
        ClassifierSummary: {
            /**
             * Format: date-time
             * @description When the classifier was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description A brief description of the classifier
             * @example Tag general subjects like people, places, and things
             */
            description: Record<string, never> | null;
            /**
             * @description The ID of the classifier
             * @example sajl1kih6emtwozh8y0zenkj
             */
            id: string;
            /**
             * @description The name of the classifier
             * @example general-tagging
             */
            name: string;
            /** @description The classification provider used by the classifier */
            provider: components["schemas"]["ClassificationProviderSummary"];
            /**
             * Format: date-time
             * @description When the classifier was last updated
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ConfigSchemaItems: {
            /**
             * @description The maximum allowable length of the array
             * @default null
             * @example 10
             */
            maxLength: Record<string, never> | null;
            /**
             * @description The minimum allowable length of the array
             * @default null
             * @example 1
             */
            minLength: Record<string, never> | null;
            /** @description The properties of the items, if the items are objects */
            properties: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description The field type of the items
             * @example string
             */
            type: string;
        };
        ConfigSchemaValue: {
            /**
             * @description A description of the field
             * @example The name of the user
             */
            description: Record<string, never> | null;
            /**
             * @description Whether the field is immutable
             * @example true
             */
            immutable: Record<string, never> | null;
            /** @description The item schema, if the field type is an array */
            items: components["schemas"]["ConfigSchemaItems"] | null;
            /**
             * @description The label of the field
             * @example Name
             */
            label: string;
            /**
             * @description The maximum allowable length of the field, if the field type supports length constraints
             * @default null
             * @example 10
             */
            maxLength: Record<string, never> | null;
            /**
             * @description The minimum allowable length of the field, if the field type supports length constraints
             * @default null
             * @example 1
             */
            minLength: Record<string, never> | null;
            /** @description The properties of the field, if the field type is an object */
            properties: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description Whether the field is required
             * @example true
             */
            required: boolean;
            /**
             * @description The field type
             * @example string
             */
            type: string;
        };
        CreateClassifier: {
            /**
             * @description A brief description of the classifier
             * @example Tag general subjects like people, places, and things
             */
            description: Record<string, never> | null;
            /**
             * @description The ID of the model to use for the classifier
             * @example anthropic/claude-haiku-4-5-20251001
             */
            modelId: string;
            /**
             * @description The input values to use for the model
             * @example {
             *       "name": "John Doe"
             *     }
             */
            modelInput?: Record<string, never>;
            /**
             * @description The name of the classifier
             * @example general-tagging
             */
            name: string;
        };
        CreateMediaContainer: {
            /**
             * @description Names of classifiers to run on the uploaded asset after processing
             * @example [
             *       "general-tagging"
             *     ]
             */
            classifiersOnUpload?: string[];
            /**
             * @description The MIME type of the primary asset
             * @example image/jpeg
             * @enum {string}
             */
            mimeType: "image/jpg" | "image/jpeg" | "image/png" | "image/gif" | "image/webp";
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name?: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path?: string;
            /**
             * @description The ID of the storage unit to use. If not provided, the default storage unit will be used.
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            storageUnitId?: string;
        };
        CreateMediaContainerResponse: {
            /**
             * Format: date-time
             * @description The date and time the upload URL expires.
             * @example 2025-11-14T23:09:41.289Z
             */
            expiresAt: string;
            /**
             * @description The ID of the media container
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path: string;
            /**
             * @description The status of the media container
             * @example WAITING_FOR_UPLOAD
             * @enum {string}
             */
            status: "WAITING_FOR_UPLOAD" | "PROCESSING" | "READY" | "FAILED" | "PARTIALLY_FAILED" | "DELETED";
            /**
             * @description The signed URL to upload the asset with.
             * @example https://longpoint.example.com/api/media/abc123/upload?token=abcdefghijklmnopqrst
             */
            url: string;
        };
        CreateSearchIndex: {
            /**
             * @description Whether to make the new index the active index.
             * @default false
             * @example true
             */
            active: boolean;
            /**
             * @description Provider-specific configuration for the index
             * @example {}
             */
            config?: Record<string, never>;
            /**
             * @description The fully qualified ID of the embedding model to use for the index. Leave blank to use the vector provider's embedding model, if supported.
             * @example openai/text-embedding-3-small
             */
            embeddingModelId?: string;
            /**
             * @description The name of the index
             * @example my-index
             */
            name: string;
            /**
             * @description The ID of the vector provider to use for the index
             * @example pinecone
             */
            vectorProviderId: string;
        };
        CreateStorageConfig: {
            /**
             * @description Provider-specific configuration
             * @example {}
             */
            config?: Record<string, never>;
            /**
             * @description The name of the storage config
             * @example App UGC
             */
            name: string;
            /**
             * @description The storage provider ID
             * @example storage-s3
             */
            providerId: string;
        };
        CreateStorageUnit: {
            /**
             * @description Whether this should be the default storage unit
             * @default false
             * @example false
             */
            isDefault: boolean;
            /**
             * @description The name of the storage unit
             * @example My Storage Unit
             */
            name: string;
            /**
             * @description The storage config ID to use
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            storageConfigId: string;
        };
        DeleteMediaContainer: {
            /**
             * @description Whether to permanently delete the media container
             * @default false
             * @example false
             */
            permanently: Record<string, never>;
        };
        DirectoryTreeItem: {
            /**
             * @description The full path to the directory
             * @example /skate-tricks/kickflips
             */
            path: string;
            /**
             * @description The type of the tree item
             * @example DIRECTORY
             * @enum {string}
             */
            treeItemType: "DIRECTORY";
            /**
             * @description The URL to list the contents of the directory
             * @example https://longpoint.example.com/api/media/tree?path=/skate-tricks/kickflips
             */
            url: string;
        };
        GenerateContainerLink: {
            /**
             * @description The ID of the media container
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            containerId: string;
            /**
             * @description The height of the transformed image in pixels
             * @example 600
             */
            h?: number;
            /**
             * @description The width of the transformed image in pixels
             * @example 800
             */
            w?: number;
        };
        GenerateMediaLinks: {
            /** @description The containers to generate links for */
            containers: components["schemas"]["GenerateContainerLink"][];
        };
        ListStorageUnitsResponse: {
            /** @description The storage units in the response */
            items: components["schemas"]["StorageUnitSummary"][];
            /** @description The metadata for pagination */
            metadata: components["schemas"]["PaginationMetadata"];
        };
        MediaAsset: {
            /**
             * @description The aspect ratio of the media asset, if applicable
             * @example 1.777777
             */
            aspectRatio: number | null;
            /** @description The classifier runs for the media asset */
            classifierRuns: components["schemas"]["ClassifierRun"][];
            /**
             * @description The height of the media asset in pixels, if applicable
             * @example 100
             */
            height: number | null;
            /**
             * @description The ID of the media asset
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description The MIME type of the media asset
             * @example image/jpeg
             * @enum {string}
             */
            mimeType: "image/jpg" | "image/jpeg" | "image/png" | "image/gif" | "image/webp";
            /**
             * @description The size of the media asset in bytes
             * @example 100
             */
            size: number | null;
            /**
             * @description The status of the media asset
             * @example WAITING_FOR_UPLOAD
             * @enum {string}
             */
            status: "WAITING_FOR_UPLOAD" | "PROCESSING" | "READY" | "FAILED";
            /**
             * @description The URL of the media asset
             * @example https://longpoint.example.com/storage/default/abc123/original.jpg
             */
            url: string | null;
            /**
             * @description The width of the media asset in pixels, if applicable
             * @example 100
             */
            width: number | null;
        };
        MediaAssetVariants: {
            /** @description The primary media asset */
            primary: components["schemas"]["MediaAsset"];
        };
        MediaContainer: {
            /**
             * Format: date-time
             * @description When the media container was created
             * @example 2025-11-25T14:34:46.062Z
             */
            createdAt: string;
            /**
             * @description The ID of the media container
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path: string;
            /**
             * @description The status of the media container
             * @example WAITING_FOR_UPLOAD
             * @enum {string}
             */
            status: "WAITING_FOR_UPLOAD" | "PROCESSING" | "READY" | "FAILED" | "PARTIALLY_FAILED" | "DELETED";
            /**
             * @description The primary media type.
             * @example IMAGE
             * @enum {string}
             */
            type: "IMAGE";
            /**
             * @description The accessible media assets in the container
             * @example {
             *       "primary": {
             *         "id": "okie3r17vhfswyyp38v9lrsl",
             *         "variant": "PRIMARY",
             *         "status": "READY",
             *         "mimeType": "image/jpeg",
             *         "width": 1920,
             *         "height": 1080,
             *         "size": 950120,
             *         "aspectRatio": 1.777777,
             *         "url": "https://longpoint.example.com/storage/default/abc123/original.jpg"
             *       }
             *     }
             */
            variants: components["schemas"]["MediaAssetVariants"];
        };
        MediaContainerSummary: {
            /**
             * Format: date-time
             * @description When the media container was created
             * @example 2025-11-25T14:34:46.062Z
             */
            createdAt: string;
            /**
             * @description The ID of the media container
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path: string;
            /**
             * @description The status of the media container
             * @example WAITING_FOR_UPLOAD
             * @enum {string}
             */
            status: "WAITING_FOR_UPLOAD" | "PROCESSING" | "READY" | "FAILED" | "PARTIALLY_FAILED" | "DELETED";
        };
        MediaContainerTreeItem: {
            /**
             * Format: date-time
             * @description When the media container was created
             * @example 2025-11-25T14:34:46.062Z
             */
            createdAt: string;
            /**
             * @description The ID of the media container
             * @example r2qwyd76nvd98cu6ewg8ync2
             */
            id: string;
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path: string;
            /**
             * @description The status of the media container
             * @example WAITING_FOR_UPLOAD
             * @enum {string}
             */
            status: "WAITING_FOR_UPLOAD" | "PROCESSING" | "READY" | "FAILED" | "PARTIALLY_FAILED" | "DELETED";
            /**
             * @description The type of the tree item
             * @example MEDIA
             * @enum {string}
             */
            treeItemType: "MEDIA";
        };
        MediaTree: {
            /**
             * @description The items in the tree
             * @example [
             *       {
             *         "type": "DIRECTORY",
             *         "content": {
             *           "path": "/skate-tricks/kickflips/bloopers",
             *           "url": "https://longpoint.example.com/api/media/tree?path=/skate-tricks/kickflips/bloopers"
             *         }
             *       },
             *       {
             *         "type": "MEDIA",
             *         "content": {
             *           "id": "123",
             *           "name": "Stairs",
             *           "type": "IMAGE",
             *           "status": "READY",
             *           "createdAt": "2025-10-16T00:00:00.000Z"
             *         }
             *       },
             *       {
             *         "type": "MEDIA",
             *         "content": {
             *           "id": "123",
             *           "name": "Long gap",
             *           "type": "IMAGE",
             *           "status": "READY",
             *           "createdAt": "2025-10-16T00:00:00.000Z"
             *         }
             *       }
             *     ]
             */
            items: (components["schemas"]["DirectoryTreeItem"] | components["schemas"]["MediaContainerTreeItem"])[];
            /**
             * @description The media tree path
             * @example /skate-tricks/kickflips
             */
            path: string;
        };
        PaginationMetadata: {
            /**
             * @description The cursor to the next page
             * @example jN1a2VuZHMA
             */
            nextCursor: string | null;
            /**
             * @description The link to the next page
             * @example https://example.com/api/items?cursor=jN1a2VuZHMA
             */
            nextLink: string | null;
            /**
             * @description The number of items per page
             * @example 100
             */
            pageSize: number;
        };
        SearchIndex: {
            /**
             * @description Whether the index is active
             * @default false
             * @example true
             */
            active: boolean;
            /** @description The configuration values for the index */
            config: {
                [key: string]: unknown;
            } | null;
            /**
             * @description The model used by the index to generate vector embeddings
             * @example {
             *       "id": "text-embedding-3-small",
             *       "name": "Text Embedding 3 Small",
             *       "fullyQualifiedId": "openai/text-embedding-3-small",
             *       "provider": {
             *         "id": "openai",
             *         "name": "OpenAI",
             *         "image": null,
             *         "needsConfig": false
             *       }
             *     }
             */
            embeddingModel: components["schemas"]["AiModelSummary"] | null;
            /**
             * @description The ID of the index
             * @example o1jnduht9zboa0w1dcjfzqi5
             */
            id: string;
            /**
             * @description Whether the index is currently indexing
             * @example false
             */
            indexing: boolean;
            /**
             * @description The date and time the index last ran successfully
             * @example 2025-01-01T00:00:00.000Z
             */
            lastIndexedAt: string | null;
            /**
             * @description The number of media items indexed
             * @example 100
             */
            mediaIndexed: number;
            /**
             * @description The name of the index
             * @example my-index
             */
            name: string;
            /**
             * @description The vector database provider used by the index
             * @example {
             *       "id": "pinecone",
             *       "name": "Pinecone",
             *       "image": null
             *     }
             */
            vectorProvider: components["schemas"]["VectorProviderShort"];
        };
        SearchQuery: {
            /**
             * @description The search query text
             * @example sunset beach
             */
            query: string;
        };
        SearchResults: {
            /** @description The search results */
            results: components["schemas"]["MediaContainerSummary"][];
            /**
             * @description Total number of results
             * @example 5
             */
            total: number;
        };
        SetupStatus: {
            /**
             * @description Whether the first time setup is complete
             * @example false
             */
            isFirstTimeSetup: boolean;
        };
        StorageConfig: {
            /**
             * @description Configuration for the provider
             * @example {}
             */
            config: Record<string, never> | null;
            /**
             * Format: date-time
             * @description When the config was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description The ID of the storage config
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            id: string;
            /**
             * @description The name of the storage config
             * @example App UGC
             */
            name: string;
            /** @description The storage provider the config is for */
            provider: components["schemas"]["StorageProviderSummary"];
            /**
             * @description Number of storage units using this config
             * @example 3
             */
            storageUnitCount: number;
            /**
             * Format: date-time
             * @description When the config was last updated
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        StorageConfigSummary: {
            /**
             * @description The ID of the storage config
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            id: string;
            /**
             * @description The name of the storage config
             * @example App UGC
             */
            name: string;
            /** @description The storage provider the config is for */
            provider: components["schemas"]["StorageProviderSummary"];
            /**
             * @description Number of storage units using this config
             * @example 3
             */
            storageUnitCount: number;
        };
        StorageProvider: {
            /**
             * @description The schema for the storage provider config
             * @example {
             *       "folderName": {
             *         "label": "Folder Name",
             *         "type": "string",
             *         "required": true
             *       }
             *     }
             */
            configSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description The ID of the storage provider
             * @example local
             */
            id: string;
            /** @description An icon image of the storage provider */
            image: string | null;
            /**
             * @description The display name of the storage provider
             * @example Local
             */
            name: string;
        };
        StorageProviderShort: {
            /**
             * @description The ID of the storage provider
             * @example local
             */
            id: string;
            /**
             * @description The display name of the storage provider
             * @example Local
             */
            name: string;
        };
        StorageProviderSummary: {
            /**
             * @description The ID of the storage provider
             * @example local
             */
            id: string;
            /** @description An icon image of the storage provider */
            image: string | null;
            /**
             * @description The display name of the storage provider
             * @example Local
             */
            name: string;
        };
        StorageUnit: {
            /**
             * @description Provider-specific configuration (decrypted)
             * @example {}
             */
            config: Record<string, never> | null;
            /**
             * Format: date-time
             * @description When the storage unit was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description The ID of the storage unit
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            id: string;
            /**
             * @description Whether this is the default storage unit
             * @example true
             */
            isDefault: boolean;
            /**
             * @description The name of the storage unit
             * @example Local Default
             */
            name: string;
            /** @description The storage provider */
            provider: components["schemas"]["StorageProviderShort"];
            /**
             * Format: date-time
             * @description When the storage unit was last updated
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        StorageUnitSummary: {
            /**
             * Format: date-time
             * @description When the storage unit was created
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description The ID of the storage unit
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            id: string;
            /**
             * @description Whether this is the default storage unit
             * @example true
             */
            isDefault: boolean;
            /**
             * @description The name of the storage unit
             * @example Local Default
             */
            name: string;
            /** @description The storage provider */
            provider: components["schemas"]["StorageProviderShort"];
            /**
             * Format: date-time
             * @description When the storage unit was last updated
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        SystemStatus: {
            /**
             * @description Total number of ready media containers
             * @example 150
             */
            totalContainers: number;
        };
        UpdateAiProviderConfig: {
            /**
             * @description The configuration values for the AI provider
             * @example {
             *       "apiKey": "1234567890"
             *     }
             */
            config: Record<string, never>;
        };
        UpdateClassifier: {
            /**
             * @description A brief description of the classifier
             * @example Tag general subjects like people, places, and things
             */
            description?: Record<string, never> | null;
            /**
             * @description The ID of the model to use for the classifier
             * @example anthropic/claude-haiku-4-5-20251001
             */
            modelId?: string;
            /**
             * @description The input values to use for the model
             * @example {
             *       "name": "John Doe"
             *     }
             */
            modelInput?: Record<string, never>;
            /**
             * @description The name of the classifier
             * @example general-tagging
             */
            name?: string;
        };
        UpdateMediaContainer: {
            /**
             * @description A descriptive name for the underlying media
             * @example Blissful Fields
             */
            name?: string;
            /**
             * @description The directory path of the media container
             * @example /
             */
            path?: string;
        };
        UpdateStorageConfig: {
            /**
             * @description Provider-specific configuration
             * @example {}
             */
            config?: Record<string, never>;
            /**
             * @description The name of the storage config
             * @example App UGC
             */
            name?: string;
            /**
             * @description The storage provider ID
             * @example storage-s3
             */
            providerId?: string;
        };
        UpdateStorageUnit: {
            /**
             * @description Whether this should be the default storage unit
             * @default false
             * @example false
             */
            isDefault: boolean;
            /**
             * @description The name of the storage unit
             * @example My Storage Unit
             */
            name?: string;
            /**
             * @description The storage config ID to use
             * @example mbjq36xe6397dsi6x9nq4ghc
             */
            storageConfigId?: string;
        };
        UpdateVectorProviderConfig: {
            /**
             * @description The configuration values for the vector provider
             * @example {
             *       "apiKey": "1234567890"
             *     }
             */
            config: Record<string, never>;
        };
        VectorProvider: {
            /**
             * @description The configuration values for the vector provider
             * @example {
             *       "apiKey": "sk-1234567890"
             *     }
             */
            config: {
                [key: string]: unknown;
            } | null;
            /** @description The schema for the vector provider config */
            configSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description The ID of the vector provider
             * @example pinecone
             */
            id: string;
            /**
             * @description An optional icon image of the vector provider
             * @example https://www.gstatic.com/pantheon/images/aiplatform/model_garden/icons/icon-pinecone-v2.png
             */
            image: string | null;
            /** @description The schema for the vector provider index config */
            indexConfigSchema: {
                [key: string]: components["schemas"]["ConfigSchemaValue"];
            };
            /**
             * @description The name of the vector provider
             * @example Pinecone
             */
            name: string;
            /**
             * @description Whether the vector provider is capable of embedding documents without an external model
             * @example true
             */
            supportsEmbedding: boolean;
        };
        VectorProviderShort: {
            /**
             * @description The ID of the vector provider
             * @example pinecone
             */
            id: string;
            /**
             * @description An optional icon image of the vector provider
             * @example https://www.gstatic.com/pantheon/images/aiplatform/model_garden/icons/icon-pinecone-v2.png
             */
            image: string | null;
            /**
             * @description The name of the vector provider
             * @example Pinecone
             */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"][];
                };
            };
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"];
                };
            };
        };
    };
    listAiProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProvider"][];
                };
            };
        };
    };
    getAiProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProvider"];
                };
            };
            /** @description AI provider not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "AI provider with id r2qwyd76nvd98cu6ewg8ync2 not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    updateAiProviderConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAiProviderConfig"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProvider"];
                };
            };
        };
    };
    listClassificationProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationProvider"][];
                };
            };
        };
    };
    listClassifiers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifierSummary"][];
                };
            };
        };
    };
    createClassifier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassifier"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Classifier"];
                };
            };
        };
    };
    getClassifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classifierId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Classifier"];
                };
            };
            /** @description The classifier was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Classifier with id ukt4084q1kaqmsq74f2fxg43 not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    deleteClassifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classifierId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The classifier was deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The classifier was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Classifier with id ukt4084q1kaqmsq74f2fxg43 not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    updateClassifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classifierId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassifier"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Classifier"];
                };
            };
            /** @description The classifier was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Classifier with id ukt4084q1kaqmsq74f2fxg43 not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    createMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaContainer"];
            };
        };
        responses: {
            /** @description Use the returned signed url to upload the original asset. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMediaContainerResponse"];
                };
            };
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                containerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                };
            };
            /** @description Media container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Media container with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                containerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMediaContainer"];
            };
        };
        responses: {
            /** @description The media container was deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                containerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMediaContainer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                };
            };
            /** @description Media container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Media container with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
            /** @description The media container already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_ALREADY_EXISTS",
                     *       "messages": [
                     *         "Media container with name \"My Container\" already exists at path \"/\""
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                /** @description The token used to upload the asset */
                token: string;
            };
            header?: never;
            path: {
                containerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset was uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Media container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Media container with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    generateLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMediaLinks"];
            };
        };
        responses: {
            /** @description The generated links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTree: {
        parameters: {
            query?: {
                /** @description The path to get the tree for */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contents of the media tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTree"];
                };
            };
        };
    };
    searchMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
        };
    };
    listSearchIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchIndex"][];
                };
            };
        };
    };
    createSearchIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSearchIndex"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchIndex"];
                };
            };
        };
    };
    deleteSearchIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVectorProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorProvider"][];
                };
            };
        };
    };
    updateVectorProviderConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVectorProviderConfig"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorProvider"];
                };
            };
        };
    };
    listStorageConfigs: {
        parameters: {
            query: {
                providerId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfigSummary"][];
                };
            };
        };
    };
    createStorageConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageConfig"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfig"];
                };
            };
        };
    };
    getStorageConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfig"];
                };
            };
            /** @description Storage provider config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage provider config with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    deleteStorageConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The storage config was deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Storage provider config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage provider config with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
            /** @description Storage provider config is in use and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "INVALID_INPUT",
                     *       "messages": [
                     *         "Storage provider config mbjq36xe6397dsi6x9nq4ghc cannot be deleted because it is used by 2 storage unit(s)"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    updateStorageConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageConfig"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfig"];
                };
            };
            /** @description Storage provider config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage provider config with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    listStorageProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageProvider"][];
                };
            };
        };
    };
    listStorageUnits: {
        parameters: {
            query?: {
                /** @description The ID of the storage config to filter by */
                configId?: string;
                /** @description The cursor to the next page */
                cursor?: string;
                /** @description The number of items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListStorageUnitsResponse"];
                };
            };
        };
    };
    createStorageUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageUnit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUnit"];
                };
            };
        };
    };
    getStorageUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageUnitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUnit"];
                };
            };
            /** @description Storage unit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage unit with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    deleteStorageUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageUnitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The storage unit was deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Storage unit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage unit with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
            /** @description Storage unit is in use and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "INVALID_INPUT",
                     *       "messages": [
                     *         "Storage unit mbjq36xe6397dsi6x9nq4ghc cannot be deleted because it has media containers"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    updateStorageUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageUnitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageUnit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUnit"];
                };
            };
            /** @description Storage unit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "errorCode": "RESOURCE_NOT_FOUND",
                     *       "messages": [
                     *         "Storage unit with id mbjq36xe6397dsi6x9nq4ghc not found"
                     *       ]
                     *     } */
                    "application/json": {
                        errorCode?: string;
                        messages?: string[];
                    };
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
